### ISSUE TITLE
Project is almost out of space on codespaces.

### ISSUE THREAD

**Issue by Vesper-arch** [Vesper-arch/Slay-The-Spire-in-Python#22] opened 2024-01-02 04:52 UTC
A notification pops up every once in a while that says something along the lines of "Disk space available is under 5%. Please free up more space for the codespace to work properly." I do not know if there is anything thing I can delete that doesn't completely screw up to project and I don't want to pay for it.

**Comment by miketwo** [comment] 2024-01-02 17:27
A couple ideas:

- Make sure you're not accumulating usage on old Codespaces. See them all here: https://github.com/codespaces and delete any unused ones.
- [Get a usage report](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/viewing-your-github-codespaces-usage) and see where the usage is coming from.
- Make sure your working directory is as clean as possible. `git clean -ndx` (replace 'n' with 'f' if you agree with what it would do), and `git gc --aggressive --prune=now` can help.
- The repo is fairly large because there are several downloaded libraries that have been committed (under `.pythonlibs`). These should not be in the repo at all, but just deleting won't help because they remain in the git history. [The process of cleaning a repo is rather involved](https://stackoverflow.com/a/2116892). But that may help reduce the size. 
- There's also some questionable dependencies being installed (Django, numpy, pandas,...) These are enormous and probably unused? Figuring out where they're coming from and removing them would help. This is known as "(dependency) tree shaking"
- If all else fails, consider local development. With VSCode and Docker, you can use the `.devcontainer` to develop in an isolated environment locally with no quotas.

**Comment by Vesper-arch** [comment] 2024-01-02 17:30
The libraries are there because Replit felt like downloading all of them without me doing anything and I don't know if I can delete them without Replit re-installing them.

**Comment by Vesper-arch** [comment] 2024-01-02 17:31
I only have 1 codespace open

**Comment by Vesper-arch** [comment] 2024-01-02 17:33
Also, aside from basic merges, pulls, and pushes, I don't have much experience with git. So, could you explain the git commands more so I don't accidentally mess up the repo?

**Comment by miketwo** [comment] 2024-01-03 01:29
Why do you need both Replit and Codespaces? Don't they do the same thing?

**Comment by Vesper-arch** [comment] 2024-01-03 01:31
I am using Replit to host it so that people can play it without having to go through the whole devcontainer process

**Comment by miketwo** [comment] 2024-01-03 01:58
That's a good idea. But Replit also allows code editing and git syncing, so why Codespaces?

**Comment by Vesper-arch** [comment] 2024-01-03 04:50
Just a better customizable workspace imo. Much more powerful and doesn't complain when I have a line longer than 80 characters. Plus, Zen mode.

**Comment by Vesper-arch** [comment] 2024-01-13 19:30
why:
![Screenshot 2024-01-13 11 28 52](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/assets/137581120/3ef0aa6e-3439-4d33-9b4c-002cf68298be)

**Comment by Vesper-arch** [comment] 2024-01-13 19:30
I thought cleaning out the pythonlibs folder would work but its somehow worse now.

**Comment by miketwo** [comment] 2024-01-13 20:27
Hmm... what does the dropdown under storage say is the cause?

**Comment by Vesper-arch** [comment] 2024-01-13 20:32
It just shows this 
![Screenshot 2024-01-13 12 31 54](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/assets/137581120/b9f93aad-cab3-4e69-afee-43ca24050652)

**Comment by miketwo** [comment] 2024-01-13 20:49
Ah well that's useless. Hmm... [There's a bunch of suggestions here](https://docs.github.com/en/codespaces/troubleshooting/troubleshooting-included-usage). Maybe it's VSCode extensions? Try this inside the codespace to see: `du -h -s ~/.vscode-remote/extensions`

**Comment by Vesper-arch** [comment] 2024-01-13 20:53
Using that command shows that it takes up 197mb

**Comment by miketwo** [comment] 2024-01-13 20:59
eh... fairly chunky... .2GB/day is 6GB/month. That's not everything but that's part of it. You might want to slim down your extensions. 

Maybe poke around with `du -a | sort -n -r | head -n 10` -- that shows the top 10 biggest folders in the current directory. So like, go looking for big stuff and see where it is?

**Comment by Vesper-arch** [comment] 2024-01-13 21:03
Yea, .python libs is by far the biggest one. It is 208,776mb large

**Comment by Vesper-arch** [comment] 2024-01-13 21:04
or what ever the measure is

**Comment by miketwo** [comment] 2024-01-13 21:16
kb, so that's ~209MB. Still not ridiculous, but that's another 6GB/mo.... so we're up to 12GB/mo with just those two folders.

I'd suggest looking at what VSCode extensions you can dump, and poking around pythonlibs to see if there's stuff installed that's not needed (like numpy or something).

**Comment by miketwo** [comment] 2024-01-13 21:18
15GB/mo is only 500MB a day though -- that's pretty tiny. You'll have to really keep an eye on it to stay below the limit. I'd consider running locally as a cheaper/less hassle option.

**Comment by Vesper-arch** [comment] 2024-01-14 16:29
Can I still do all go the stuff with git while on a local environment?

**Comment by miketwo** [comment] 2024-01-14 16:46
Pushing/branching/merging/rebasing....yeah. All of git can be done locally. A local env is really no different than a codespace, it's just that you have to manage it yourself. Installing packages/extensions/etc. Setting up your credentials in git. But it's not bad. Especially if using the VSCode devcontainer and especially if using Linux. Everything but git will be set up automatically.

**Comment by Vesper-arch** [comment] 2024-01-14 16:54
Ok, I'll switch to local

**Comment by miketwo** [comment] 2024-01-14 17:30
Google any error message you get. Let me know if you can't find the answer to something.

**Comment by Vesper-arch** [comment] 2024-01-15 19:32
Do I have to use docker to start on a local env or do I just clone it.

**Comment by Vesper-arch** [comment] 2024-01-15 20:03
nvm, got it working

**Comment by Vesper-arch** [comment] 2024-01-15 20:05
Nope, what the hell just happened:
![items py - Slay-The-Spire-in-Python  Dev Container_ Python 3  - Visual Studio Code 1_15_2024 12_05_13 PM](https://github.com/Vesper-arch/Slay-The-Spire-in-Python/assets/137581120/43c73bbe-530e-469a-8691-c6129361c5bb)

**Comment by miketwo** [comment] 2024-01-16 00:28
lol probably a Linux-to-Windows thing. Windows treats everything as executable (because viruses are fun, hah), and Linux has a way of distinguishing those. Try `git config core.filemode false` and see if that fixes it.

**Comment by miketwo** [comment] 2024-01-16 00:30
You also may need to make sure you're on a clean checkout of main, so `git clean -ndx` (to see what would get deleted) and `git clean -fdx` to do it. Maybe a `git reset --hard` too if there's still changes showing. Just muscle it back to a clean working directory.

**Comment by Vesper-arch** [comment] 2024-01-16 00:35
The first 3 did nothing but the last cleaned out everything and now it just has to pull _71_ commits from main. lol

**Comment by Vesper-arch** [comment] 2024-01-16 00:43
Ok, just got it working. How do I get the changes I made on my laptop over to the desktop?

**Comment by miketwo** [comment] 2024-01-16 01:06
```bash
# On one computer...
git checkout -b some_branch_name   # switches to a new branch, creating it on-the-fly
(commit the changes. I personally like to use `git gui`, but you can use whatever)
git push origin  # it may force you to do something like git push --upstream-something, and that's ok. Just do that if it complains
# Then on the receiving computer
git fetch --all  # gets all branches
git checkout some_branch_name
```

**Comment by Vesper-arch** [comment] 2024-01-18 01:03
Whelp, gonna have to wait until next month because codespaces ran out of storage

**Closed** 2024-01-19 04:00 UTC
Labels: urgent
